language: node_js
node_js:
    - 10.23.0
script:
    - npm run build
    - docker --version
    - echo "Beginning docker build"
    - docker build -t udagaram-feed-api .
    - docker tag udagaram-feed-api renjithtech6/udagaram-feed-api

after_success:
    - echo "About to create container in Docker registry"
    - echo "$D_PSWD" | docker login -u "$D_UNAME" --password-stdin
    - docker push renjithtech6/udagaram-feed-api
